### ISSUE TITLE
Scrivener 3 Compatibility

### ISSUE THREAD

**Issue by iandol** [mnott/texdown#1]
Hi Mattias, 

Scrivener 3 has been out for a while now, do you have any plans to update this project to work with the modified Scrivener 3 project format (UUIDs replace all folder names, more cleanly parseable)?

**Comment by mnott** [comment]
Has been implemented and published right now. Thanks for the suggestion. Scrivener 2 backwards compatibility is maintained if you add -2 to the command line. This does not include snapshot handling, as we have never implemented it for Scrivener 2 in the first place.

**Comment by iandol** [comment]
Wow, quick work, thanks!
